[package]
name = 'xmlparser'
version = '0.5.1'
authors = [ "Sal Bakra'a <SalBakraa@gmail.com>" ]
edition = '2018'
repository = 'https://github.com/SalBakraa/xmlparser'
license = 'GPL-3.0-or-later'

[dependencies]
cty = "0.2.1"
phf = { version = "0.9", features = ["macros"] } # For compile time hashmaps

[build-dependencies]
bindgen = "0.59.1"
